# -*- coding: utf-8 -*-
"""Copy of PlayStore Review PipeLine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9yf4u4w2rfERyI2D0F2CC-uObkDSw-g
"""

import os
import pandas as pd
from google_play_scraper import reviews, Sort
from openai import OpenAI

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage

import markdown
from datetime import datetime

def main():

    app_package = "com.csam.icici.bank.imobile"

    result, token = reviews(
        app_package,
        lang='en',
        country='in',
        sort=Sort.NEWEST,
        count=2000
    )

    df = pd.DataFrame(result)

    print(len(df))
    df.head()

    all_reviews = []
    result, token = reviews(app_package, count=200)
    all_reviews.extend(result)

    while token and len(all_reviews) < 2000:
        result, token = reviews(app_package, continuation_token=token)
        all_reviews.extend(result)

    df = pd.DataFrame(all_reviews)

    print(len(df))

    df = df[['content', 'score', 'at', 'appVersion']]
    df.head()

    df['at'] = pd.to_datetime(df['at'])
    df['date'] = df['at'].dt.date

    df[['at', 'date']].head()

    last_15_days = df['date'].max() - pd.Timedelta(days=15)
    df = df[df['date'] >= last_15_days]

    print(df['date'].min(), "to", df['date'].max())
    print(len(df))

    df['is_negative'] = df['score'] <= 3
    df.head()

    grouped = df.groupby(['date', 'appVersion']).agg(
        avg_rating=('score', 'mean'),
        review_count=('score', 'count'),
        negative_pct=('is_negative', 'mean')
    ).reset_index()

    grouped['negative_pct'] = grouped['negative_pct'] * 100

    grouped.head(10)

    MIN_REVIEWS_PER_VERSION = 15

    valid_versions = grouped.groupby('appVersion')['review_count'].sum()
    valid_versions = valid_versions[valid_versions >= MIN_REVIEWS_PER_VERSION].index

    grouped = grouped[grouped['appVersion'].isin(valid_versions)]

    grouped = grouped.sort_values(by=['appVersion', 'date'], ascending=[True, True])
    grouped.head(20)

    output = ""

    for version in grouped['appVersion'].unique():
        output += f"\nVersion {version}:\n"
        temp = grouped[grouped['appVersion'] == version]

        for _, row in temp.iterrows():
            output += f"- {row['date']} → Rating: {round(row['avg_rating'],2)} | Reviews: {row['review_count']} | Negative: {round(row['negative_pct'],1)}%\n"

    print(output)



    import os
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    prompt = f"""
    You are analyzing app performance trends.

    Your goal is to identify the MOST IMPORTANT issues.

    Rules:
    1. Prioritize events based on:
    - High review volume AND
    - Sharp rating drop
    2. Ignore low-volume anomalies unless extremely severe
    3. Clearly distinguish between:
    - Major issues (high impact)
    - Minor anomalies (low impact)
    4. Do NOT give equal importance to all dips

    Output:
    - Major Issues (ranked)
    - Minor Anomalies (if any)
    - Overall Interpretation

    If a sharp drop occurs but review volume is low (<10), classify it as a "low-confidence anomaly" and do not treat it as a major issue unless similar patterns repeat.

    Data:
    {output}
    """

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0.3
    )

    result = response.choices[0].message.content

    print(result)

    selection_prompt = f"""
    You are analyzing app performance data across versions and dates.

    Your task:
    Identify the 6 most important (version, date) pairs that require deeper investigation.

    Selection criteria:
    - focus only on 2 versions with most volume
    - Sudden drop in rating
    - Spike in negative reviews
    - Unusual increase in review volume
    - Prioritize recent days (last 3–5 days)
    - Prioritize high-volume versions

    Rules:
    - Ignore low-sample anomalies unless extreme
    - Return exactly 6 pairs
    - Output ONLY in this format (no explanation):

    Version | Date

    Example:
    30.1 | 2026-03-16

    Return ONLY 6 lines.
    Do not include any explanation or extra text.

    Data:
    {output}
    """

    selection_response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {"role": "user", "content": selection_prompt}
        ],
        temperature=0.2
    )

    selection_text = selection_response.choices[0].message.content

    print(selection_text)

    



    events = []

    lines = selection_text.strip().split("\n")

    for line in lines:
        if "|" in line:
            version, date = line.split("|")
            events.append({
                "version": version.strip(),
                "date": date.strip()
            })

    print("EVENTS:", events)

    # =========================
    # STEP 0: Ensure date exists
    # =========================


    df['at'] = pd.to_datetime(df['at'])
    df['date'] = df['at'].dt.date


    # =========================
    # STEP 1: Build best_days
    # =========================
    best_days = {}

    for version in grouped['appVersion'].unique():

        temp = grouped[
            (grouped['appVersion'] == version) &
            (grouped['review_count'] >= 10)
        ]

        if len(temp) > 0:
            best_row = temp.sort_values('avg_rating', ascending=False).iloc[0]
            best_days[str(version).strip()] = str(best_row['date'])

    print("BEST DAYS:", best_days)


    # =========================
    # STEP 2: Parse events
    # =========================
    events = []

    lines = selection_text.strip().split("\n")

    for line in lines:
        if "|" in line:
            version, date = line.split("|")
            events.append({
                "version": version.strip(),
                "date": date.strip()
            })

    print("EVENTS:", events)


    # =========================
    # STEP 3: MAIN LOOP
    # =========================
    for e in events:

        version = str(e["version"]).strip()
        date = e["date"]

        best_date = best_days.get(version)

        print("\n========================")
        print("Version:", version)
        print("Bad date:", date)
        print("Best date:", best_date)

        # SAFETY
        if not best_date:
            print("❌ No best day found, skipping")
            continue

        # ---------------------
        # BAD DAY REVIEWS
        # ---------------------
        df_event = df[
            (df['appVersion'].astype(str) == version) &
            (df['date'].astype(str) == date) &
            (df['score'] <= 3)
        ]

        # ---------------------
        # GOOD DAY REVIEWS
        # ---------------------
        df_good = df[
            (df['appVersion'].astype(str) == version) &
            (df['date'].astype(str) == best_date) &
            (df['score'] <= 3)
        ]

        # ---------------------
        # CLEAN TEXT
        # ---------------------
        df_event = df_event[df_event['content'].str.len() > 6]
        df_event = df_event[df_event['content'].str.split().str.len() >= 3]

        df_good = df_good[df_good['content'].str.len() > 6]
        df_good = df_good[df_good['content'].str.split().str.len() >= 3]

        # ---------------------
        # OUTPUT CHECK
        # ---------------------
        print(f"Bad day reviews: {len(df_event)}")
        print(f"Good day reviews: {len(df_good)}")

    why_results = []

    for event in events:

        version = str(event["version"]).strip()
        date = event["date"]
        best_date = best_days.get(version)

        print(f"\nProcessing: Version {version} | Date {date}")

        if not best_date:
            print("No best day found, skipping")
            continue

        # -------------------------
        # BAD DAY REVIEWS
        # -------------------------
        df_event = df[
            (df['appVersion'].astype(str) == version) &
            (df['date'].astype(str) == date) &
            (df['score'] <= 3)
        ]

        # -------------------------
        # GOOD DAY REVIEWS
        # -------------------------
        df_good = df[
            (df['appVersion'].astype(str) == version) &
            (df['date'].astype(str) == best_date) &
            (df['score'] <= 3)
        ]

        # -------------------------
        # CLEAN
        # -------------------------
        df_event = df_event[df_event['content'].str.len() > 6]
        df_event = df_event[df_event['content'].str.split().str.len() >= 2]

        df_good = df_good[df_good['content'].str.len() > 6]
        df_good = df_good[df_good['content'].str.split().str.len() >= 2]

        # -------------------------
        # SKIP SMALL DATA
        # -------------------------
        if len(df_event) < 5:
            print("Skipped (too few bad reviews)")
            continue

        # -------------------------
        # SAMPLE
        # -------------------------
        bad_sample = df_event.sample(n=min(40, len(df_event)), random_state=42)
        good_sample = df_good.sample(n=min(15, len(df_good)), random_state=42) if len(df_good) > 0 else pd.DataFrame()

        bad_reviews = bad_sample['content'].tolist()
        good_reviews = good_sample['content'].tolist()

        # -------------------------
        # TEXT FORMAT
        # -------------------------
        bad_reviews_text = "\n".join([f"{i+1}. {r}" for i, r in enumerate(bad_reviews)])
        good_reviews_text = "\n".join([f"{i+1}. {r}" for i, r in enumerate(good_reviews)])

        # -------------------------
        # PROMPT (FIXED)
        # -------------------------
        why_prompt = f"""
    You are a senior product analyst.

    Context:
    Version: {version}
    Bad Day: {date}
    Best Day: {best_date}

    Data:
    - Bad day reviews: {len(bad_reviews)}
    - Best day reviews: {len(good_reviews)}

    Task:
    1. Identify top 1-2 major issues on bad day
    2. Compare with best day:
    - If issues existed before → explain how they worsened
    - If not → mark them as new issues
    3. Focus only on technical/app issues (ignore support/operations)
    4. Be sharp and concise

    Output format:
    - Key Issues:
    - What Changed:
    - Conclusion:

    Bad Day Reviews:
    {bad_reviews_text}

    Best Day Reviews:
    {good_reviews_text if len(good_reviews) > 0 else "No meaningful negative reviews"}
    """

        # -------------------------
        # CALL OPENAI
        # -------------------------
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[{"role": "user", "content": why_prompt}],
            temperature=0.2
        )

        why_output = response.choices[0].message.content

        print("Done ✅")

        why_results.append({
            "version": version,
            "date": date,
            "best_date": best_date,
            "analysis": why_output
        })

    for r in why_results:
        print("\n---------------------------")
        print(f"Version {r['version']} | {r['date']}")
        print(r['analysis'])

    final_prompt = f"""
    You are a senior product analyst generating a structured app performance report based on user reviews.

    You are given:
    1. Quantitative analysis (WHAT happened: trends, dips, volumes)
    2. Root cause analysis (WHY it happened: issue categories, patterns, examples)

    Your task is to generate a clear, structured report.

    Title:
    Last 15 Days PlayStore Review Analysis

    ---

    Section 1: Overall Summary (2–3 lines)
    - Summarize overall app performance across versions
    - Highlight which version is stable vs problematic

    ---

    Section 2: Key Version Analysis (ONLY top 2 high-volume versions)

    For EACH version, follow EXACT structure:

    Version <X>

    Trend Summary:
    - Describe how ratings evolved over last 15 days (stable / volatile / improving / declining)
    - Mention only meaningful movements (not daily noise)

    Anomaly 1: <Date – dd Mon format>
    - What happened: (rating drop + scale/volume context)
    - ...
    - What changed vs best day:(Were issues new OR did existing issues increase?)
    - ...
    - Root Cause:1–2 major issue categories (clear naming)
    - ...
    - Examples:(Include 1–2 short real user complaints (paraphrased, not raw dump))
    - ...

    Anomaly 2: <Date – dd Mon format>
    - Same structure as above

    Rules for anomaly selection:
    - Prioritize high-volume + high-impact days
    - Ignore low-volume noise unless extreme

    ---

    Section 3: Other Versions
    - 2–3 line summary
    - Mention only if:
        - Very low volume OR
        - No meaningful trend

    ---

    Strict Rules:
    - DO NOT repeat raw numbers excessively
    - DO NOT describe every date
    - DO NOT add recommendations
    - Focus only on insights and changes
    - Be sharp, concise, and non-generic
    - Use business language (not casual wording)
    - Avoid phrases like “users reported issues” — be specific
    ----------------------

    QUANT ANALYSIS:
    {result}

    ----------------------

    ROOT CAUSE ANALYSIS:
    {why_results}
    """

    final_response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[
            {"role": "user", "content": final_prompt}
        ],
        temperature=0.3
    )

    final_report = final_response.choices[0].message.content

    print(final_report)



    # Get top 2 versions by total reviews
    top_versions = grouped.groupby('appVersion')['review_count'].sum().nlargest(2).index

    df_plot = grouped[grouped['appVersion'].isin(top_versions)]

    plt.figure(figsize=(12, 5))

    for version in top_versions:
        temp = df_plot[df_plot['appVersion'] == version]
        temp = temp.sort_values('date')

        # Normalize bubble sizes
        sizes = (temp['review_count'] / temp['review_count'].max()) * 300

        # Line
        plt.plot(
            temp['date'],
            temp['avg_rating'],
            marker='o',
            linewidth=2,
            label=f"Version {version}"
        )

        # Bubbles
        plt.scatter(
            temp['date'],
            temp['avg_rating'],
            s=sizes,
            alpha=0.6
        )



    # ✅ Show ALL dates (but readable)
    unique_dates = sorted(df_plot['date'].unique())
    plt.xticks(unique_dates, rotation=45, fontsize=8)

    # 🔥 Vertical guide lines (key improvement)
    for d in unique_dates:
        plt.axvline(x=d, color='gray', linestyle='--', alpha=0.1)

    # Labels
    plt.xlabel("Date", fontsize=10)
    plt.ylabel("Average Rating", fontsize=10)

    # Title + subtitle
    plt.title(
        "App Rating Trend (Top Versions)\n(Bubble size represents number of reviews)",
        fontsize=12,
        weight='bold'
    )

    # Grid (only horizontal for cleanliness)
    plt.grid(axis='y', alpha=0.2)

    # Legend
    plt.legend(frameon=False)

    plt.ylim(2.0, 5.2)

    plt.tight_layout(rect=[0, 0.05, 1, 1])
    plt.savefig("rating_trend.png", dpi=300)
    plt.close()






    html_content = markdown.markdown(final_report)

    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6;">
    {html_content}
    </body>
    </html>
    """

    sender_email = os.getenv("EMAIL_SENDER")
    app_password = os.getenv("EMAIL_PASSWORD")
    receiver_emails = os.getenv("RECEIVER_EMAILS").split(",")
    receiver_emails = [e.strip() for e in receiver_emails]

    today = datetime.now().strftime("%d %b %Y")

    # Outer container
    msg = MIMEMultipart("related")
    msg["Subject"] = f" iMobile Playstore Review Analysis - {today} - [AI Generated]"
    msg["From"] = sender_email
    msg["To"] = ", ".join(receiver_emails)

    # Inner container (IMPORTANT)
    msg_alt = MIMEMultipart("alternative")
    msg.attach(msg_alt)

    # HTML content with image
    html_content_with_image = f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #000;">

    <h2>15 Days iMobile PlayStore Analysis</h2>

    <p><b>Rating Trend (Top Versions):</b></p>
    <img src="cid:rating_graph" style="max-width:600px;"><br><br>

    {html_content}

    </body>
    </html>
    """

    # Attach HTML to alternative container (NOT directly to msg)
    msg_alt.attach(MIMEText(html_content_with_image, "html"))

    # Attach image
    with open("rating_trend.png", "rb") as img:
        mime_img = MIMEImage(img.read())
        mime_img.add_header("Content-ID", "<rating_graph>")
        mime_img.add_header("Content-Disposition", "inline", filename="rating_trend.png")
        msg.attach(mime_img)

    server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
    server.login(sender_email, app_password)
    server.sendmail(sender_email, receiver_emails, msg.as_string())
    server.quit()

    print("Email sent successfully 🚀")

if __name__ == "__main__":
    main()
